### ISSUE TITLE
Arviz warning: Shape validation failed: input_shape: (1, 1000), minimum_shape: (chains=2, draws=4)

### ISSUE THREAD

**Issue by Fuhan-Yang** [CDCgov/cfa-immunization-uptake-projection#160]
Warning shows up when using this config: 

```
diagnostics:
  model: [HillModel]
  forecast_date: [2024-02-03]
  plot: []
  table: [print_model_summary]

```
The shape of `print_model_summary` is checked and correct. Maybe it's the Xarray output from arviz reporting the warning?
